import React, { useState, useEffect } from "react";
import { useApp } from "../context/AppContext.tsx";
import { Task } from "../types.ts";
import {
  Sparkles,
  AlertTriangle,
  BrainCircuit,
  Zap,
  Clock,
  CheckCircle2,
  Calendar,
  Smile,
  Plus,
  Compass,
  ArrowUpRight,
  Flame,
  Check
} from "lucide-react";
import axios from "axios";

export const DashboardView: React.FC = () => {
  const { tasks, habits, goals, coachAdvice, createTask, updateTask, coachLoading } = useApp();
  const [dailyTimeline, setDailyTimeline] = useState<any[]>([]);
  const [timelineLoading, setTimelineLoading] = useState(false);

  // Quick Add task state
  const [quickTitle, setQuickTitle] = useState("");
  const [quickDeadline, setQuickDeadline] = useState("");
  const [quickPriority, setQuickPriority] = useState<"low" | "medium" | "high">("medium");
  const [quickEstimatedTime, setQuickEstimatedTime] = useState("60");
  const [quickAddLoading, setQuickAddLoading] = useState(false);
  const [addSuccess, setAddSuccess] = useState(false);

  // Fetch Daily schedule generated by Gemini API
  useEffect(() => {
    fetchTimeline();
  }, [tasks, habits]);

  const fetchTimeline = async () => {
    try {
      setTimelineLoading(true);
      const res = await axios.get("/api/ai/daily-schedule");
      setDailyTimeline(res.data);
    } catch (err) {
      console.error("Failed to fetch daily schedule:", err);
    } finally {
      setTimelineLoading(false);
    }
  };

  const handleQuickAdd = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!quickTitle || !quickDeadline) return;
    setQuickAddLoading(true);
    try {
      await createTask({
        title: quickTitle,
        deadline: new Date(quickDeadline).toISOString(),
        priority: quickPriority,
        estimatedTime: Number(quickEstimatedTime),
        category: "Work",
        difficulty: "medium",
        subtasks: [],
      });
      setQuickTitle("");
      setQuickDeadline("");
      setAddSuccess(true);
      setTimeout(() => setAddSuccess(false), 3000);
    } catch (err) {
      console.error("Quick task add failed:", err);
    } finally {
      setQuickAddLoading(false);
    }
  };

  // Get current active priorities
  const activePriorities = tasks
    .filter((t) => t.status !== "completed")
    .sort((a, b) => b.priorityScore - a.priorityScore)
    .slice(0, 3);

  // Burnout level color
  const getBurnoutColor = (idx: number) => {
    if (idx > 70) return "text-rose-400 bg-rose-500/10 border-rose-500/20";
    if (idx > 40) return "text-amber-400 bg-amber-500/10 border-amber-500/20";
    return "text-emerald-400 bg-emerald-500/10 border-emerald-500/20";
  };

  return (
    <div className="space-y-8 pb-12">
      {/* Welcome Hero Grid */}
      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        {/* Coach Advice Core suggestions */}
        <div className="lg:col-span-2 glass-panel rounded-3xl p-6 relative overflow-hidden flex flex-col justify-between border border-gray-800">
          <div className="absolute top-0 right-0 w-48 h-48 bg-indigo-500/5 rounded-full blur-2xl"></div>
          <div>
            <div className="flex items-center gap-2 text-indigo-400 text-xs font-semibold tracking-wider uppercase mb-3">
              <BrainCircuit className="w-4 h-4" /> AI Productivity Coach
            </div>
            {coachLoading ? (
              <div className="space-y-3 py-4">
                <div className="h-4 bg-gray-800 rounded w-1/4 animate-pulse"></div>
                <div className="h-6 bg-gray-800 rounded w-3/4 animate-pulse"></div>
                <div className="h-4 bg-gray-800 rounded w-5/6 animate-pulse"></div>
              </div>
            ) : coachAdvice ? (
              <div className="space-y-4">
                <div className="flex items-center gap-3">
                  <div className={`px-3 py-1 rounded-full text-xs font-bold border ${getBurnoutColor(coachAdvice.burnoutIndex)}`}>
                    Burnout Risk: {coachAdvice.burnoutIndex}/100
                  </div>
                  <span className="text-xs text-gray-400">Calculated via task density and deadline proximity</span>
                </div>
                <h3 className="text-base text-gray-200 font-medium leading-relaxed">
                  {coachAdvice.burnoutWarning}
                </h3>
                <div className="p-3 bg-gray-900/40 border border-gray-800/50 rounded-xl">
                  <p className="text-xs text-indigo-300 italic flex items-center gap-1.5">
                    <Sparkles className="w-3.5 h-3.5" /> Habit Stacking Advice: {coachAdvice.habitAdvice}
                  </p>
                </div>
              </div>
            ) : (
              <p className="text-xs text-gray-500 py-4">Generating behavioral analysis and burnout checks...</p>
            )}
          </div>

          {/* Staggered general tips */}
          {coachAdvice && coachAdvice.generalTips && (
            <div className="mt-6 pt-5 border-t border-gray-900 grid grid-cols-1 md:grid-cols-2 gap-4">
              {coachAdvice.generalTips.slice(0, 2).map((tip, idx) => (
                <div key={idx} className="flex gap-2.5 text-xs text-gray-400 leading-normal">
                  <span className="w-5 h-5 rounded-lg bg-gray-900 border border-gray-800 flex items-center justify-center shrink-0 text-indigo-400 font-semibold font-display">
                    {idx + 1}
                  </span>
                  <p>{tip}</p>
                </div>
              ))}
            </div>
          )}
        </div>

        {/* Quick Add Form */}
        <div className="glass-panel rounded-3xl p-6 border border-gray-800 flex flex-col justify-between">
          <div className="mb-4">
            <h3 className="text-sm font-bold text-white uppercase tracking-wider flex items-center gap-2">
              <Zap className="w-4 h-4 text-amber-400" /> Smart Task Ingest
            </h3>
            <p className="text-xs text-gray-400 mt-1">
              Add any deadline below. Gemini instantly calculates smart priority and risk parameters.
            </p>
          </div>

          <form onSubmit={handleQuickAdd} className="space-y-3">
            <input
              type="text"
              required
              placeholder="Task title, e.g. Final Pitch Deck"
              value={quickTitle}
              onChange={(e) => setQuickTitle(e.target.value)}
              className="w-full bg-gray-950 border border-gray-800 rounded-xl px-3 py-2.5 text-xs text-gray-200 focus:outline-none focus:border-indigo-500 transition-colors"
            />

            <div className="grid grid-cols-2 gap-2">
              <input
                type="datetime-local"
                required
                value={quickDeadline}
                onChange={(e) => setQuickDeadline(e.target.value)}
                className="bg-gray-950 border border-gray-800 rounded-xl px-2 py-2.5 text-[11px] text-gray-300 focus:outline-none focus:border-indigo-500 transition-colors"
              />
              <select
                value={quickPriority}
                onChange={(e: any) => setQuickPriority(e.target.value)}
                className="bg-gray-950 border border-gray-800 rounded-xl px-2 py-2.5 text-[11px] text-gray-300 focus:outline-none focus:border-indigo-500 transition-colors"
              >
                <option value="low">Low Priority</option>
                <option value="medium">Medium Priority</option>
                <option value="high">High Priority</option>
              </select>
            </div>

            <div className="relative">
              <input
                type="number"
                required
                placeholder="Est. Minutes (e.g. 60)"
                value={quickEstimatedTime}
                onChange={(e) => setQuickEstimatedTime(e.target.value)}
                className="w-full bg-gray-950 border border-gray-800 rounded-xl px-3 py-2.5 text-xs text-gray-200 focus:outline-none focus:border-indigo-500 transition-colors"
              />
              <span className="absolute right-3 top-2.5 text-[10px] font-semibold text-gray-500 uppercase">
                Mins
              </span>
            </div>

            <button
              type="submit"
              disabled={quickAddLoading}
              className="w-full bg-indigo-600 hover:bg-indigo-500 text-white font-semibold py-2.5 rounded-xl text-xs flex items-center justify-center gap-1.5 transition-all shadow-md hover:shadow-indigo-600/10"
            >
              {quickAddLoading ? (
                "Analyzing via AI..."
              ) : (
                <>
                  <Plus className="w-3.5 h-3.5" /> Launch Task
                </>
              )}
            </button>
          </form>

          {addSuccess && (
            <div className="mt-2.5 text-center text-[11px] text-emerald-400 font-medium flex items-center justify-center gap-1">
              <Check className="w-3 h-3" /> Successfully prioritized via Gemini!
            </div>
          )}
        </div>
      </div>

      {/* Main Core Content Grid */}
      <div className="grid grid-cols-1 lg:grid-cols-5 gap-6 items-start">
        {/* Priorities & Deadlines */}
        <div className="lg:col-span-3 space-y-6">
          <div className="flex items-center justify-between">
            <h3 className="font-display font-semibold text-lg text-white">Today's Priority Focus</h3>
          </div>

          <div className="space-y-4">
            {activePriorities.length === 0 ? (
              <div className="glass-panel rounded-2xl p-8 text-center border border-gray-900">
                <CheckCircle2 className="w-8 h-8 text-indigo-400 mx-auto mb-2" />
                <p className="text-xs text-gray-400">All caught up! No active pending priorities.</p>
              </div>
            ) : (
              activePriorities.map((task) => (
                <div
                  key={task.id}
                  className="glass-panel rounded-2xl p-5 border border-gray-800/80 hover:border-gray-700/80 transition-all flex items-start justify-between gap-4 group"
                >
                  <div className="flex-1 min-w-0">
                    <div className="flex items-center gap-2 mb-2 flex-wrap">
                      <span className="text-[10px] font-bold text-indigo-400 uppercase tracking-wider bg-indigo-500/10 border border-indigo-500/15 px-2 py-0.5 rounded-md">
                        AI Weight: {task.priorityScore}
                      </span>
                      {task.riskScore > 40 && (
                        <span className="text-[10px] font-bold text-rose-400 uppercase tracking-wider bg-rose-500/10 border border-rose-500/15 px-2 py-0.5 rounded-md flex items-center gap-0.5 animate-pulse">
                          <AlertTriangle className="w-2.5 h-2.5" /> High Miss Risk
                        </span>
                      )}
                    </div>

                    <h4 className="text-sm font-semibold text-white group-hover:text-indigo-400 transition-colors">
                      {task.title}
                    </h4>
                    <p className="text-xs text-gray-400 mt-1 line-clamp-2">{task.description}</p>

                    <div className="flex items-center gap-4 mt-3 flex-wrap">
                      <span className="text-[10px] text-gray-400 flex items-center gap-1">
                        <Clock className="w-3.5 h-3.5 text-gray-500" /> Est: {task.estimatedTime}m
                      </span>
                      <span className="text-[10px] text-gray-400 flex items-center gap-1">
                        <Calendar className="w-3.5 h-3.5 text-gray-500" /> Due:{" "}
                        {new Date(task.deadline).toLocaleDateString("en-US", {
                          month: "short",
                          day: "numeric",
                          hour: "2-digit",
                          minute: "2-digit",
                        })}
                      </span>
                    </div>

                    {/* AI recommended start notification */}
                    <div className="mt-3.5 p-2.5 bg-gray-950/40 rounded-xl border border-gray-900/60 flex items-start gap-2">
                      <BrainCircuit className="w-3.5 h-3.5 text-indigo-400 shrink-0 mt-0.5" />
                      <p className="text-[10px] text-gray-300 italic leading-relaxed">
                        <span className="font-semibold text-indigo-300">Contextual Prompt:</span> "You still need around {task.estimatedTime}m to complete this. Start by {new Date(task.recommendedStartTime).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })} to comfortably avoid delay."
                      </p>
                    </div>
                  </div>

                  {/* Circle Check Action */}
                  <button
                    onClick={() => updateTask(task.id, { status: "completed" })}
                    className="p-1 rounded-full bg-gray-900 border border-gray-800 text-gray-500 hover:text-emerald-400 hover:border-emerald-500 transition-all self-center"
                  >
                    <CheckCircle2 className="w-5 h-5" />
                  </button>
                </div>
              ))
            )}
          </div>
        </div>

        {/* Gemini Daily Chronological Timeline Schedule */}
        <div className="lg:col-span-2 space-y-6">
          <div className="flex items-center justify-between">
            <h3 className="font-display font-semibold text-lg text-white flex items-center gap-2">
              <Calendar className="w-4.5 h-4.5 text-indigo-400" /> Optimized Daily Schedule
            </h3>
            <button
              onClick={fetchTimeline}
              className="text-[10px] font-semibold text-indigo-400 hover:text-indigo-300 flex items-center gap-0.5 uppercase tracking-wide"
            >
              Recalibrate
            </button>
          </div>

          <div className="glass-panel rounded-3xl p-5 border border-gray-800">
            {timelineLoading ? (
              <div className="space-y-4 py-8">
                {[1, 2, 3].map((i) => (
                  <div key={i} className="flex gap-4 animate-pulse">
                    <div className="w-16 h-4 bg-gray-800 rounded"></div>
                    <div className="flex-1 h-4 bg-gray-800 rounded"></div>
                  </div>
                ))}
              </div>
            ) : dailyTimeline.length === 0 ? (
              <p className="text-xs text-gray-500 text-center py-8">Create tasks to generate AI scheduler timeline.</p>
            ) : (
              <div className="relative pl-4 border-l border-gray-800 space-y-6 py-2">
                {dailyTimeline.map((slot, index) => {
                  let badgeColor = "bg-gray-800 text-gray-400";
                  if (slot.type === "task") badgeColor = "bg-indigo-500/10 text-indigo-400 border border-indigo-500/20";
                  if (slot.type === "habit") badgeColor = "bg-rose-500/10 text-rose-400 border border-rose-500/20";
                  if (slot.type === "break") badgeColor = "bg-emerald-500/10 text-emerald-400 border border-emerald-500/20";

                  return (
                    <div key={index} className="relative group flex items-start gap-3.5">
                      {/* Bullet */}
                      <span className="absolute -left-[20.5px] top-1.5 w-3 h-3 rounded-full bg-gray-900 border-2 border-indigo-500 ring-4 ring-gray-950"></span>

                      <div className="min-w-[65px] pt-0.5">
                        <span className="font-mono text-xs font-semibold text-indigo-400">
                          {slot.time}
                        </span>
                      </div>

                      <div className="flex-1">
                        <span className={`inline-block text-[9px] font-bold uppercase tracking-wider px-1.5 py-0.5 rounded-md mb-1.5 ${badgeColor}`}>
                          {slot.type}
                        </span>
                        <p className="text-xs text-gray-300 font-medium group-hover:text-indigo-400 transition-colors">
                          {slot.item}
                        </p>
                      </div>
                    </div>
                  );
                })}
              </div>
            )}
          </div>
        </div>
      </div>
    </div>
  );
};
